site_name: Intuit Developer FAQ
site_url: https://developer.intuit.com
site_favicon: favicon.ico
repo_url: https://github.intuit.com/abisalehalliprasan/intuit-developer-faq
docs_dir: docs
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [fonts.js]
pages:
# Introduction:
- ['index.md', 'Overview', 'About']
- ['basics.md', 'FAQ', 'RingCentral Basics']
- ['oauth.md', 'FAQ', 'Authentication & Authorization']
- ['account.md', 'FAQ', 'Account Info']
- ['voice_ringout.md', 'FAQ', 'Voice via RingOut']
- ['voice_webrtc.md', 'FAQ', 'Voice via WebRTC']
- ['voice_recording.md', 'FAQ', 'Voice Call Recordings']
- ['sms.md', 'FAQ', 'SMS']
- ['fax.md', 'FAQ', 'Fax']
- ['api_usage_plan.md', 'FAQ', 'API Usage Plan']
- ['call_log.md', 'FAQ', 'Call Log']
- ['phone_numbers.md', 'FAQ', 'Phone Numbers']
- ['notifications_subscriptions.md', 'FAQ', 'Notifications & Subscription']
- ['webhooks.md', 'FAQ', 'Webhooks']
- ['errors.md', 'FAQ', 'Errors']
- ['sdks_programming.md', 'FAQ', 'SDKs & Programming']
- ['integration.md', 'FAQ', 'Integration']
- ['legacy_ringout_faxout_apis.md', 'FAQ', 'Upgrading from Legacy APIs']