site_name: Intuit Developer FAQ
site_url: https://developer.intuit.com
site_favicon: favicon.ico
repo_url: https://github.intuit.com/abisalehalliprasan/intuit-developer-faq
docs_dir: docs
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [fonts.js]
